### ISSUE TITLE
.NET Standard V2.1 support

### ISSUE THREAD

**Issue by ArrowtheArcher** [ShaunCurtis/CEC.Routing#1]
Is there currently any way to add this package's nuget to client side blazor project that uses netstandard2.1? If not then is there any plans to support netstandard?

**Comment by ShaunCurtis** [comment]
Sorry, but no to both.  I assume standard you mean .dotcore 2.1 release and not .net standard.  You are welcome to lift what code you want and use it in your project or pull it and compile and fix it on 2.1.

**Comment by ArrowtheArcher** [comment]
Alright, thanks anyways.

**Comment by ShaunCurtis** [comment]
Now published as netstandard2.1
