### ISSUE TITLE
netstandard2.1 compability 

### ISSUE THREAD

**Issue by pureggerstefan** [ShaunCurtis/CEC.Routing#2]
Is there a reason why netcoreapp3.1 is needed? Because e.g. hosted web assembly projects need netstandard2.1 and compability for this would be nice.

Best Regards, 
Stefan

**Comment by ShaunCurtis** [comment]
Will take a look and get back.

**Comment by ShaunCurtis** [comment]
Updated and republished to netstandard2.1.  Nuget package updated.  See Wiki for updates.
