### ISSUE TITLE
Using the NavigationManager.NavigateTo($"/page"); is causing issues with the cancel dialog

### ISSUE THREAD

**Issue by AndyCC25** [ShaunCurtis/CEC.Routing#6]
I'm using a dropdown to run navigation but the cancel dialog doesn't appears:
```c#
public async Task GoToPage(string page)
        {
           NavigationManager.NavigateTo($"/{subSystem}");
            StateChanged?.Invoke();
        }
```

and I have the event:
```c#
 protected virtual void RouterSessionServiceNavigationCancelled(object sender, EventArgs e)
        {
            ConfirmDialog!.Show(); // this is a simple ok cancel dialog
            StateChanged!.Invoke();
        }
```

No matter if I click the cancel the navigation already happens

**Comment by ShaunCurtis** [comment]
Hi,

Are you implementing IRecordRouterComponent interface on your page, and setting up in OnInitialized :

this.RouteUrl = this.NavManager.Uri;
this.RouterSessionService.ActiveComponent = this;
this.RouterSessionService.NavigationCancelled += OnNavigationCancelled;

Routing will only cancel if the IRecordRouterComponent.IsClean property is set to false.

I need to see more code to see what's going wrong
