### ISSUE TITLE
To assess the RouterSessionService in application to use across different pages

### ISSUE THREAD

**Issue by PreetiShaw** [ShaunCurtis/CEC.Routing#8]
Hi Team,

Is there any way that I can inject RouterSessionService in base component so that I can use it in any edit pages without injecting there. Also can I implement IRecordRoutingComponent in base component and then I can inherit that base component in all edit pages.

Request  you to review it and kindly help to provide the solution.

Thanks in advance

**Comment by sorgeas** [comment]
To be more specific, it's currently impossible to mock the RouterSessionService, as it doesn't have a parameterless constructor. This is an issue as we use Bunit for unit testing our components, and we cannot mock this dependency.

**Comment by ShaunCurtis** [comment]
Will have a look.  There's an updated Net5 currently being worked onm

**Comment by ShaunCurtis** [comment]
The answer is no for the following reason.  `RouterSessionService` is a service and needs to define the other *Services* it requires on startup in it's constructor.   It's not designed to load manually.  With a parameterless constructor, the service container will load it that way and you'll have a broken service until you make a manual load call from somewhere.   Feel free to take my code and construct your own Router.
