### ISSUE TITLE
PreferExactMatches

### ISSUE THREAD

**Issue by scottkuhl** [ShaunCurtis/CEC.Routing#9]
The RecordRouter should add support for PreferExactMatches.  This may be needed by projects upgrading from 3.X to 5.0 of Blazor.

[Blazor: Route precedence logic changed in Blazor apps](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/blazor-routing-logic-changed)

`<RecordRouter AppAssembly="@typeof(Program).Assembly" PreferExactMatches="true">`

**Comment by scottkuhl** [comment]
It appears there are several changes that need to be updated to bring the RecordRouter up to date to match the version that is in Blazor v5.

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs

**Comment by ShaunCurtis** [comment]
Noted.  There's an updated Net5 version being loaded at the moment

**Comment by ShaunCurtis** [comment]
Updated version released.  It uses the Net5 router as the base code.
